# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# See https://goreleaser.com/customization/ for more information.
version: 2
project_name: halsecur

before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    binary: halsecur
    main: ./
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      # The v prefix is stripped by goreleaser, so we need to add it back.
      # https://goreleaser.com/customization/templates/#fnref:version-prefix
      - "-X 'bisecur/version.Version={{ .Tag }}' -X 'bisecur/version.BuildDate={{ .Date }}'"

dockers_v2:
  - images:
      - "ghcr.io/halacs/halsecur"
#      - "halacs/halsecur"
    tags:
      - "{{ .Tag }}"
      - "v{{ .Major }}"
      - "v{{ .Major }}.{{ .Minor }}"
      - "latest"
    labels:
      "org.opencontainers.image.created": "{{ .Date }}"
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.version": "{{ .Version }}"
    build_args:
      "VERSION": "{{ .Tag }}"
      "DATE": "{{ .Date }}"
    platforms:
      - linux/amd64

archives:
  - formats: [ 'binary' ]
    name_template: >-
      {{ .ProjectName }}_{{- tolower .Os }}_{{ .Arch }}

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: github-native